### ISSUE TITLE
Organisation des dossiers

### ISSUE THREAD

**Issue by nicolaslechenic** [vincent56250/verte_nature_bs#6]
Que penses tu d'organiser ton projet en sous-dossiers : 

**exemple** : 

```txt
|_ assets
•  |_ images  
•  •  |_ logos
•  •  |_ slider  
•  |_ javascripts
•  |_ stylesheets
|- index.html
|- contact.html
|_ ...

```

**Comment by vincent56250** [comment]
ça va etre long je sais pas comment faire sans tout reprendre
je vais devoir changer tous les liens
